# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Build and install collection for antsibull-docs
      - ansible-galaxy collection build --force
      - ansible-galaxy collection install m1yag1-globus-*.tar.gz --force
      # Generate RST from module docstrings
      - mkdir -p docs/rst
      - chmod og-w docs/rst
      - antsibull-docs --config-file docs/antsibull-docs.cfg collection --cleanup everything --use-current --dest-dir docs/rst m1yag1.globus
      # Fix title case
      - find docs/rst -name '*.rst' -exec sed -i 's/M1Yag1\.Globus/m1yag1.globus/g' {} \;
      - find docs/rst -name '*.rst' -exec sed -i 's/M1yag1/m1yag1/g' {} \;
      # Copy Sphinx config files
      - cp docs/conf.py docs/index.rst docs/rst/

sphinx:
  configuration: docs/rst/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
