---
namespace: m1yag1
name: globus
version: 0.5.1
readme: README.md
authors:
  - Ansible Globus Collection Contributors

description: >
  Ansible collection for managing Globus infrastructure including endpoints,
  collections, groups, compute endpoints, and workflows. Supports both Globus CLI
  and client credentials authentication methods for comprehensive Globus Connect
  Server automation.

license:
  - Apache-2.0

tags:
  - globus
  - data_transfer
  - research_computing
  - hpc
  - cloud
  - storage
  - automation
  - infrastructure

dependencies: {}

repository: https://github.com/m1yag1/ansible-globus
documentation: https://github.com/m1yag1/ansible-globus/blob/main/README.md
homepage: https://github.com/m1yag1/ansible-globus
issues: https://github.com/m1yag1/ansible-globus/issues

# Build ignore patterns
build_ignore:
  # Compiled/cache files
  - "*.pyc"
  - "*.retry"
  - "__pycache__"
  - "*.egg-info"
  - "*.log"
  - ".ruff_cache"

  # Version control
  - ".git"
  - ".gitignore"
  - ".gitattributes"
  - ".github"

  # Virtual environments
  - ".venv"
  - "venv"
  - ".tox"

  # Testing
  - "tests"
  - ".pytest_cache"
  - ".coverage"
  - "htmlcov"
  - "coverage_html"
  - "coverage.xml"
  - "pytest.ini"
  - "conftest.py"
  - "tox.ini"
  - "bandit-report.json"

  # Test state files
  - ".auth_policy_id"
  - ".compute_endpoint_id"
  - ".compute_flow_id"
  - ".compute_function_id"

  # Development tooling
  - ".pre-commit-config.yaml"
  - ".yamllint.yml"
  - ".ansible-lint"
  - "ansible.cfg"
  - "pyproject.toml"
  - "uv.lock"
  - "Makefile"

  # Infrastructure/CI
  - "infra"
  - "scripts"
  - ".flows"

  # Documentation (internal)
  - "_docs"
  - "docs"
  - "TESTING_GUIDE.md"
  - "RELEASING.md"
  - "CONTRIBUTING.md"
  - "examples/INTEGRATION_TESTING.md"

  # Build artifacts
  - "build"
  - "dist"
  - "_build"

  # OS files
  - ".DS_Store"
  - "Thumbs.db"
  - ".ansible"

  # Changelog tooling
  - "cliff.toml"
